FROM golang:1.18 AS compilador
WORKDIR /app
COPY . ./
RUN go mod init hello
RUN go build -o /app/hello
#EXPOSE

### Inicio MultiStaging
FROM alpine:3.15.9
WORKDIR /app
# se você configura o WORKDIR, você pode utilizar o ./ para executar os programas e comandos dentro do container
COPY --from=compilador /app/hello /app/hello
ENV APP="hello_world"
ARG GIROPOPS="strigus"
RUN echo "O Giropops é: $GIROPOPS"
ENTRYPOINT ["./hello"]
