apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntu-deployment
  name: ubuntu-deployment
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ubuntu-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: ubuntu-deployment
    spec:
      containers:
      - image: ubuntu:latest
        name: ubuntu-licao1
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.25"
            memory: 128Mi
        command: ["tail", "-f", "/dev/null"] # adiciona este comando
        livenessProbe: #habilitando a probe, faz verificações de health do pod
          exec:
            command:
              - "ping"
              - "-c 8"
              - "8.8.8.8"
              - "> /ok.txt"
          initialDelaySeconds: 10 #quanto tempo esperar após o inicio do pod, para iniciar as verificações
          periodSeconds: 10 #tempo de espera entre as checagens
          timeoutSeconds: 5 #quanto tempo pode demorar pra responder
          failureThreshold: 3 # quantas vezes precisa falhar para validar que a aplicação parou
        readinessProbe:
          exec:
            command:
              - "uptime"
          initialDelaySeconds: 10 #quanto tempo esperar após o inicio do pod, para iniciar as verificações
          periodSeconds: 10 #tempo de espera entre as checagens
          timeoutSeconds: 5 #quanto tempo pode demorar pra responder
          failureThreshold: 3 # quantas vezes precisa falhar para validar que a aplicação parou
          successThreshold: 1 # Taxa de sucesso
        startupProbe:
          exec: 
            command:
              - "touch"
              - "/status.txt"
          initialDelaySeconds: 10 #quanto tempo esperar após o inicio do pod, para iniciar as verificações
          periodSeconds: 10 #tempo de espera entre as checagens
          timeoutSeconds: 5 #quanto tempo pode demorar pra responder
          failureThreshold: 3 # quantas vezes precisa falhar para validar que a aplicação parou
