apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.19.0
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: 0.25
            memory: 128Mi
        livenessProbe: #habilitando a probe, faz verificações de health do pod
          tcpSocket: 
            port: 80 #verifica a porta 80 do nginx
          initialDelaySeconds: 10 #quanto tempo esperar após o inicio do pod, para iniciar as verificações
          periodSeconds: 10 #tempo de espera entre as checagens
          timeoutSeconds: 5 #quanto tempo pode demorar pra responder
          failureThreshold: 3 # quantas vezes precisa falhar para validar que a aplicação parou
        readinessProbe:
          exec:
            command:
              - curl
              - -f
              - http://localhost:81/
          initialDelaySeconds: 10 #quanto tempo esperar após o inicio do pod, para iniciar as verificações
          periodSeconds: 10 #tempo de espera entre as checagens
          timeoutSeconds: 5 #quanto tempo pode demorar pra responder
          failureThreshold: 3 # quantas vezes precisa falhar para validar que a aplicação parou
          successThreshold: 1 # Taxa de sucesso
