apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret # nome do Secret
type: kubernetes.io/dockerconfigjson # tipo do Secret, neste caso é um Secret que armazena credenciais Docker
data:
  .dockerconfigjson: |  # substitua este valor pelo conteúdo do seu arquivo config.json codificado em base64
    ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJIVnBjMkpwWVc1amIyNXBPbVJqYTNKZmNHRjBYMWRCU1RGRk1VRlhkVkpKTUZCbFJWSnpSREJaVFc0d1dXWTNXUT09IgoJCX0KCX0KfQ==
    #Exemplo Seguro, chave já deletada, não é mais válida
