events { }
http {
  server {
    listen 80;
    listen 443 ssl;

    # Assuming your certificates are mounted at /etc/nginx/certs/
    ssl_certificate /etc/nginx/certs/certificado.crt; 
    ssl_certificate_key /etc/nginx/certs/chave-privada.key; 

    location / {
      return 200 'Olá, estou configurado com TLS!\n';
      add_header Content-Type text/plain;
    }
  }
}