apiVersion: v1
kind: Pod
metadata:
  name: giropops-pod
  labels:
    app: giropops
    env: dev
spec:
  containers:
  - name: giropops-container
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef: 
          name: giropops-secrets
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: giropops-secrets
          key: password

